/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'HarvestAnswerSerialMsg'
 * message type.
 */

public class HarvestAnswerSerialMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 144;

    /** Create a new HarvestAnswerSerialMsg of size 4. */
    public HarvestAnswerSerialMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new HarvestAnswerSerialMsg of the given data_length. */
    public HarvestAnswerSerialMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HarvestAnswerSerialMsg with the given data_length
     * and base offset.
     */
    public HarvestAnswerSerialMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HarvestAnswerSerialMsg using the given byte array
     * as backing store.
     */
    public HarvestAnswerSerialMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HarvestAnswerSerialMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public HarvestAnswerSerialMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HarvestAnswerSerialMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public HarvestAnswerSerialMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HarvestAnswerSerialMsg embedded in the given message
     * at the given base offset.
     */
    public HarvestAnswerSerialMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new HarvestAnswerSerialMsg embedded in the given message
     * at the given base offset and length.
     */
    public HarvestAnswerSerialMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <HarvestAnswerSerialMsg> \n";
      try {
        s += "  [result=0x"+Long.toHexString(get_result())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: result
    //   Field type: long, unsigned
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'result' is signed (false).
     */
    public static boolean isSigned_result() {
        return false;
    }

    /**
     * Return whether the field 'result' is an array (false).
     */
    public static boolean isArray_result() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'result'
     */
    public static int offset_result() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'result'
     */
    public static int offsetBits_result() {
        return 0;
    }

    /**
     * Return the value (as a long) of the field 'result'
     */
    public long get_result() {
        return (long)getUIntBEElement(offsetBits_result(), 32);
    }

    /**
     * Set the value of the field 'result'
     */
    public void set_result(long value) {
        setUIntBEElement(offsetBits_result(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'result'
     */
    public static int size_result() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'result'
     */
    public static int sizeBits_result() {
        return 32;
    }

}